export const GET_GROUP = 'GROUP/GET GROUP';
export const GET_GROUP_SUCCESS='GROUP/GET GROUP SUCCESS';
export const GET_GROUP_FAILURE='GROUP/GET GROUP FAILURE';
export const SET_GROUP = 'GROUP/SET GROUP';
export const SET_GROUP_SUCCESS='GROUP/SET GROUP SUCCESS';
export const SET_GROUP_FAILURE='GROUP/SET GROUP FAILURE';
export const CLEAR_GROUP = 'GROUP/CLEAR GROUP'
