export const GET_TEACHERS = 'TEACHERS/GET TEACHERS';
export const GET_TEACHERS_SUCCESS='TEACHERS/GET TEACHERS SUCCESS';
export const GET_TEACHERS_FAILURE='TEACHERS/GET TEACHERS FAILURE';
export const SELECT_TEACHER = 'TEACHERS/SELECT TEACHER'
