export const GET_TEACHERS = 'TEACHERS/GET TEACHERS';
export const GET_TEACHERS_SUCCESS='TEACHERS/GET TEACHERS SUCCESS';
export const GET_TEACHERS_FAILURE='TEACHERS/GET TEACHERS FAILURE';
export const SELECT_TEACHER = 'TEACHERS/SELECT TEACHER'
export const SELECT_TEACHERS_SUCCESS = 'TEACHERS/SELECT TEACHERS SUCCESS'
export const SELECT_TEACHERS_FAILURE = 'TEACHERS/SELECT TEACHERS FAILURE'